### ISSUE TITLE
Gem package on Rubygems is corrupted

### ISSUE THREAD

**Issue by aselder** [ruport/ruport#37]
Hi all,

It looks like the Gemfile on Rubygems for v.1.7.0 is corrupted.

When I go to my gemdir, there are no code files in the Ruport directory,

```
 ~/.rvm/gems/ruby-2.3.4/gems  ls ruport-1.7.0
AUTHORS     COPYING     HACKING     LICENSE     README.rdoc Rakefile
```

**Comment by Odaeus** [comment]
Thanks for reporting this! Sorry for the problem. I replied by email initially but it seems GitHub ignored it.

I've now had time to look into it. Turns out the gemspec used bash-specific wildcards to generate the files list. I've fixed that, yanked 1.7.0, and pushed 1.7.1. Hopefully that works now.
